---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sso-cluster-admins
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'allclusters-cluster-admins'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sso-cluster-auditors
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'allclusters-auditors'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
