---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhatcop-operators
  namespace: openshift-marketplace
spec:
  displayName: Red Hat CoP Community Operators
  image: 'quay.io/agoossen/redhatcop-operators-index:0.0.1'
  publisher: RedHatCoP
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: group-sync-operator
  namespace: helms-deep
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: group-sync-operator
  source: redhatcop-operators
  sourceNamespace: openshift-marketplace
