---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-logging-og
  namespace: openshift-logging
spec:
  targetNamespaces:
    - openshift-logging
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-logging
spec:
  name: cluster-logging
  channel: '5.0'
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace

