---
apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
	name: e8
	namespace: openshift-compliance
profiles:
- apiGroup: compliance.openshift.io/v1alpha1
	kind: Profile
	name: ocp4-e8
- apiGroup: compliance.openshift.io/v1alpha1
	kind: Profile
	name: rhcos4-e8
settingsRef:
	apiGroup: compliance.openshift.io/v1alpha1
	kind: ScanSetting
	name: default
