---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
spec: {}
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: openshift-logging
  namespace: openshift-logging
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - openshift-logging
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: supervisor-cluster/cluster-logging
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: openshift-logging
  name: openshift-logging-subscription
  namespace: openshift-logging
spec:
  channel: helms-deep-resources-ns/helms-deep-resources
  placement:
    placementRef:
      kind: PlacementRule
      name: openshift-logging-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: openshift-logging
  name: openshift-logging-placement-1
  namespace: openshift-logging
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'
