---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: compliance
  namespace: openshift-compliance
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - compliance
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: config/compliance
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: compliance
  name: compliance-subscription
  namespace: openshift-compliance
spec:
  channel: helms-deep-resources-ns/helms-deep-resources
  placement:
    placementRef:
      kind: PlacementRule
      name: placement-policy-compliance
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: compliance
  name: placement-policy-compliance
  namespace: openshift-compliance
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift
