---
apiVersion: v1
kind: Namespace
metadata:
  name: group-sync-operator
spec: {}
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: group-sync-operator
  namespace: group-sync-operator
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - group-sync-operator
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: supervisor-cluster/groupsync
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: group-sync-operator
  name: group-sync-operator-subscription
  namespace: group-sync-operator
spec:
  channel: helms-deep-resources-ns/helms-deep-resources
  placement:
    placementRef:
      kind: PlacementRule
      name: group-sync-operator-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: group-sync-operator
  name: group-sync-operator-placement-1
  namespace: group-sync-operator
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'
