---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-storage
  annotations:
    openshift.io/display-name: "HELMS DEEP OpenShift Data Foundation"
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-storage-og
  namespace: openshift-storage
spec:
  targetNamespaces:
    - openshift-storage
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ocs-operator
  namespace: openshift-storage
spec:
  name: ocs-operator
  channel: stable-4.6
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
