---
apiVersion: v1
kind: Namespace
metadata:
  name: group-sync-operator
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: group-sync-operator-og
  namespace: group-sync-operator
spec:
  targetNamespaces:
    - group-sync-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhatcop-operators
  namespace: openshift-marketplace
spec:
  displayName: Red Hat CoP Community Operators
  image: 'quay.io/agoossen/redhatcop-operators-index:0.0.1'
  publisher: RedHatCoP
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1
kind: Subscription
metadata:
  name: group-sync-operator
  namespace: group-sync-operator
spec:
  channel: alpha
  source: redhatcop-operators
  name: group-sync-operator
