---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: helms-deep-admins
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: all-cluster-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
