---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: preproduction-clusters
  namespace: helms-deep
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: environment
        operator: In
        values: ['preproduction']
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: production-clusters
  namespace: helms-deep
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterJoined
  clusterSelector:
    matchExpressions:
      - key: environment
        operator: In
        values: ['production']
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: development-clusters
  namespace: helms-deep
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterJoined
  clusterSelector:
    matchExpressions:
      - key: environment
        operator: In
        values: ['development']
