---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: common-managed/config/helms-deep
    apps.open-cluster-management.io/reconcile-option: merge
  name: helms-deep
  namespace: helms-deep
spec:
  channel: helms-deep-resources-ns/helms-deep-resources
  placement:
    placementRef:
      kind: PlacementRule
      name: all-remote-clusters
